jobs:
- job: build_and_test_windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      curl -sSf https://sh.rustup.rs | sh -s -- -y
      rustup component add rustfmt
    displayName: Install rust and components
  - script: |
      cargo build --verbose
    displayName: Build Collage
  - script: |
      cargo test
    displayName: Test Collage
  - script: |
      cargo fmt --all -- --check
    displayName: Check Collage rust format
- job: build_and_test_ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      curl -sSf https://sh.rustup.rs | sh -s -- -y
      rustup component add rustfmt
    displayName: Install rust and components
  - script: |
      cargo build --verbose
    displayName: Build Collage
  - script: |
      cargo test
    displayName: Test Collage
  - script: |
      cargo fmt --all -- --check
    displayName: Check Collage rust format
- job: build_and_test_macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      curl -sSf https://sh.rustup.rs | sh -s -- -y
      rustup component add rustfmt
    displayName: Install rust and components
  - script: |
      cargo build --verbose
    displayName: Build Collage
  - script: |
      cargo test
    displayName: Test Collage
  - script: |
      cargo fmt --all -- --check
    displayName: Check Collage rust format