jobs:
- job: build_and_test
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
      # TODO: re-enable once new versions are released.
      # minimum_supported_version_plus_one:
      #   rustup_toolchain: 1.32.0
      #minimum_supported_version:
      #  rustup_toolchain: 1.33.0
  steps:
  # Windows.
  - script: |
      curl -sSf https://sh.rustup.rs | sh -s -- -y
    displayName: Install rust
  - script: |
      cargo build --verbose
    displayName: Build Collage
  - script: |
      cargo test
    displayName: Test Collage
